// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Hookbin.Infrastructure.Persistence;

#nullable disable

namespace Hookbin.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hookbin.Domain.Entities.WebhookRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("IpCountry")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("IsBodyBase64")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<long?>("ProcessingTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("QueryString")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("TokenId", "Method", "ReceivedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_WebhookRequests_TokenId_Method_ReceivedAt");

                    b.HasIndex("TokenId", "ReceivedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_WebhookRequests_TokenId_ReceivedAt_Id");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TokenId", "ReceivedAt", "Id"), new[] { "Method", "Path", "SizeBytes", "IpAddress", "ContentType" });

                    b.HasIndex("TokenId", "ResponseStatusCode", "ReceivedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_WebhookRequests_TokenId_ResponseStatusCode_ReceivedAt");

                    b.ToTable("WebhookRequests", (string)null);
                });

            modelBuilder.Entity("Hookbin.Domain.Entities.WebhookToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("WebhookTokens", (string)null);
                });

            modelBuilder.Entity("Hookbin.Domain.Entities.WebhookRequest", b =>
                {
                    b.HasOne("Hookbin.Domain.Entities.WebhookToken", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Hookbin.Domain.Entities.WebhookToken", b =>
                {
                    b.OwnsOne("Hookbin.Domain.ValueObjects.CustomResponse", "CustomResponse", b1 =>
                        {
                            b1.Property<Guid>("WebhookTokenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CustomResponse_Body");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("CustomResponse_ContentType");

                            b1.Property<string>("Headers")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CustomResponse_Headers");

                            b1.Property<int>("StatusCode")
                                .HasColumnType("int")
                                .HasColumnName("CustomResponse_StatusCode");

                            b1.HasKey("WebhookTokenId");

                            b1.ToTable("WebhookTokens");

                            b1.WithOwner()
                                .HasForeignKey("WebhookTokenId");
                        });

                    b.Navigation("CustomResponse");
                });
#pragma warning restore 612, 618
        }
    }
}
